before_install:
  - docker pull pamplemousse/latex

deploy:
  - api_key:
      secure: "yKsknqlG5hfzc4/GMaCoHdcVHTcyNgO/wrx4SttE9zc2OMJHUgv0WqGOzuRn1+67t/GdzZmlgAAmM9+i7c3Vl5XDMyDy3/llURrZh4yqH87Gm3VrI07iYr3HBNwSTQmYaX77SzOAu3Pxtyky2AASAixUu+vhI1z6RcCaNLrtEVPjtb5mBupXI/5wAcL0X2zgb0LO1qW4HgiM0y6AwEL7a24vdFVvuHd8QpYsVCZA4boyLtmvTc1gcyumzjm457XPCccKKg49DAHQqAaVEYjUmlnMMnu1CrH9QdGniQASXvUcBRCB6m0OoVOp47tQansaAmpysrLTa5wBsvfH0ltbc9anVHGuUzwp9zCgh18kuXFc34bu83xMYeLvUIE6zVLS6MdwOLRyqMZNeXIG9kQyme4keptQNdBpQfW68gdt4rsIkbOuYPiGv+1upiIfbMYYBP5SMlwkXRhA0ewsBF39tpaZZ34BLJQxteMsRCCUM7SRHtvZgEFQlteq5wBh49KPM4imNW3fsvXfNcEFbdjf2gxaD2Acg9w7lFDY0sjB74K34tZEwj+gBm7i4iLNV0n9kocxAV0biirnbtMckaqVgivC4kKmR8ft8Dhu9kgM0m63YP3VK+0hVmli/neW/iZIBOAoP3BFUVp9bTkfkKyTE+/dvX8eMCsFeEogWJI1Edc="
  draft: true
  file: 'report.pdf'
  provider: releases
  skip_cleanup: true
  on:
    branches:
      only:
        -master
    tags: false

services: docker

script:
  - cd rapport_fr
  - docker run --rm -it --user $(id -u):$(id -g) -v $(pwd):/app -w /app pamplemousse/latex latexmk -bibtex -pdf rapport.tex