before_install:
- docker pull pamplemousse/latex
deploy:
- api_key:
    secure: i7vW4blwSfk03XHT5dSVNvltoC3rodaIamo3BwNQotamFVPEPqtwqswMXSotuo0fHdeX4fkrhx3Yrzu/eh4oK9WWQmInpxhteB0ttu6lXxLuQpMHoZHVdmFTYE9uwjy4/6Ri0AQGaRoghNoLfeEly3TGa0yXzWMwolY6gmrlJKMizWWKZG/V3z/1kBF0QWeqRfH5N/1Hx1sBiwW0NNvKZuElLUT+b9hK4tmUkQOWlrnLhOGk9MaiDw18Xf3ifEAr2nZgsCTgUTJy6+wlW1rmnVkKS0oiIt89Z7goCBdjVXmKLNoswF2nN/qxFj15mQ99VZPent6BtGMBBeRnBq4GDswVeb2AcnrGi5cijl23AFQV3iN711Dc1U9db9H24eeixZA1+/z5QR5S9zLztd5NUHprOv0nIXefuZ2CVVQF8J5y76A2AAytLRNxqdYVO/Au9u71Hwa5OE0Oaf/y+lJZFPktK4NnmOdDKgwAHM1ebc/HynDQ2ZR9DeAOScO7mC2QpBIukPfLozb5DUKUgnuQODEsAL8V6JlTTk7xQeEpkxLUUMHrg0e5SgwnIoO2/234zyEJp9Pto04nOz6LNqxb7WyxIT1aTneJrUmS3/fu5fBEFgQybmZDSBnJxasYkIzS2o/R4Q4QtzQ95wwrrxZMcvuB+m1d6nN01V9NZSH6F6U=
  draft: false
  file: rapport.pdf
  provider: releases
  skip_cleanup: true
  on:
    branch: master
  tags: false
services: docker
script:
- cd rapport_fr
- docker run --rm -it --user $(id -u):$(id -g) -v $(pwd):/app -w /app pamplemousse/latex
  latexmk -bibtex -pdf rapport.tex
